# Generated by Django 4.2.7 on 2023-12-20 19:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0005_alter_messages_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='participant',
            name='users',
        ),
        migrations.AddField(
            model_name='participant',
            name='users',
            field=models.ManyToManyField(related_name='users1', to=settings.AUTH_USER_MODEL),
        ),
    ]
