# Generated by Django 4.2.7 on 2023-12-20 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_messages_sender_remove_participant_users_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='room',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='base.room'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='room',
            name='participants',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participateroom', to='base.participant'),
        ),
    ]
