# Generated by Django 4.2.7 on 2023-12-20 19:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0007_participant_room_alter_room_participants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='users',
        ),
        migrations.AddField(
            model_name='participant',
            name='users',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='users1', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
