# Generated by Django 4.2.7 on 2023-12-20 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_remove_participant_users_participant_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='participants',
        ),
    ]
